# Enable forward search for 'i'nteractive login sessions in tty
[[ $- == *i* ]] && stty -ixon;

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#History Configs
SAVEHIST=10000 # Number of entries
HISTSIZE=10000
#HISTFILE=~/.zsh/history # File
setopt APPEND_HISTORY # Don't erase history
setopt EXTENDED_HISTORY # Add additional data to history like timestamp
setopt INC_APPEND_HISTORY # Add immediately
setopt HIST_FIND_NO_DUPS # Don't show duplicates in search
setopt HIST_IGNORE_SPACE # Don't preserve spaces. You may want to turn it off
setopt NO_HIST_BEEP # Don't beep
#setopt SHARE_HISTORY # Share history between session/terminals

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


#Common Aliases
alias rm='rm -i'
alias h='history'
alias vi='vim'
alias ta='tmux attach'
#Mac only
alias brewup="echo 'brew update && brew upgrade && brew cleanup' \
&& brew update && brew upgrade && brew cleanup"

# enable color support of ls and also add handy aliases
unamestr=$(uname)
if [[ "$unamestr" == 'Darwin' ]]; then
	alias ls='ls -GFh'
elif [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

export PATH="/usr/local/sbin:$PATH"
